####################################
# The following are general settings
####################################

# Experiment name, more details in Section 'Experiment Name Explanation'
NAME: HumanAct12
# Debug mode. Set to True will enter the debug mode, then the program will
# 1. use a tiny dataset for trianing and evaluation
# 2. validate more intensively
# 3. will not use `wandb logger`
DEBUG: False
# Devices. Optional: “cpu”, “gpu”
ACCELERATOR: 'gpu'
# Index of GPUs eg. [0] or [0,1,2,3]
DEVICE: [0]

#####################################
# The following are training settings
#####################################
TRAIN:
  # Model stage. Optional: "vae", "diffusion"
  STAGE: diffusion
  # Training dataset name
  DATASETS: ['Humanact12']
  # Number of dataloader workers
  NUM_WORKERS: 16
  # Size of batches
  BATCH_SIZE: 64
  # Total epochs for training
  END_EPOCH: 99999

  RESUME: '' # Resume training from this path
  # PRETRAINED_VAE: checkpoints/1109_motiontext_humanact12.ckpt # vae model path
  RETRAINED_VAE: '/home/abbas/motiontext/pre-trained/motiontext/HumanAct12/HumanAct12.ckpt'
  OPTIM:
    TYPE: AdamW # Optimizer type
    LR: 1e-4 # Learning rate
  # Ablation study configurations.
  ABLATION:
    SKIP_CONNECT: True
    PE_TYPE: mld
    DIFF_PE_TYPE: mld

#####################################
# The following are validation settings
#####################################
EVAL:
  DATASETS: ['Humanact12'] # Evaluating datasets
  BATCH_SIZE: 64 # Evaluating Batch size
  SPLIT: train

#####################################
# The following are testing settings
#####################################
TEST:
  # CHECKPOINTS: checkpoints/1109_motiontext_humanact12.ckpt # Pretrained model path
  CHECKPOINTS: '/home/abbas/motiontext/pre-trained/motiontext/HumanAct12/HumanAct12.ckpt'
  DATASETS: ['Humanact12'] # training datasets
  SPLIT: train
  BATCH_SIZE: 16 # training Batch size
  MEAN: False
  NUM_SAMPLES: 1
  FACT: 1

#####################################
# The following are basic datasets settings
#####################################
DATASET:
  JOINT_TYPE: 'Humanact12' # join type
  SAMPLER:
    REQUEST_FRAMES: null
    SAMPLING: conseq
    SAMPLING_STEP: 1
    MAX_SQE: -1
    MAX_LEN: -1
    MIN_LEN: -1
    MAX_TEXT_LEN: 20

#####################################
# The following are metric settings
#####################################
METRIC:
  TYPE: ['HUMANACTMetrics']

#####################################
# The following are training losses settings
#####################################
LOSS:
  TYPE: mld # Losses type
  LAMBDA_LATENT: 1.0e-5 # Lambda for latent Losses
  LAMBDA_KL: 1.0e-4 # Lambda for kl Losses
  LAMBDA_REC: 1.0 # Lambda for reconstruction Losses
  LAMBDA_GEN: 1.0 # Lambda for text-motion generation losses
  LAMBDA_CROSS: 1.0 # Lambda for reconstruction Losses
  LAMBDA_CYCLE: 0.0 # Lambda for cycle Losses
  LAMBDA_PRIOR: 0.0
  DIST_SYNC_ON_STEP: False # Sync Losses on step when distributed trained

#####################################
# The following are basic model settings
#####################################
model:
  target: modules_humanact12
  vae: true # whether vae model
  model_type: motiontext # model type
  condition: 'action'
  latent_dim: [1, 256] # latent dimension
  ff_size: 1024 #
  num_layers: 15 # number of layers
  num_head: 4 # number of head layers
  droupout: 0.1 # dropout rate
  activation: ReLU # activation type
  guidance_scale: 7.5 #
  guidance_uncondp: 0.1 # 0.1 0.25

#####################################
# The following are loggers settings
#####################################
LOGGER:
  SACE_CHECKPOINT_EPOCH: 100
  LOG_EVERY_STEPS: 100
  VAL_EVERY_STEPS: 100
  TENSORBOARD: True
  WANDB:
    PROJECT: null
    OFFLINE: False
    RESUME_ID: null
