motion_vae:
  # Optional: motiontext_vae, vposert_vae
  target: core.architectures.actor_vae.ActorVae
  params:
    ff_size: 1024
    num_layers: 6
    num_heads: 4
    dropout: 0.1
    normalize_before: false
    activation: 'ReLU'
    position_embedding: 'learned'
    latent_dim: ${model.latent_dim}
    nfeats: ${DATASET.NFEATS}
    ablation: ${TRAIN.ABLATION}
